apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  creationTimestamp: "2020-05-18T11:24:34Z"
  generation: 1
  name: letsencrypt
  resourceVersion: "59753561"
  selfLink: /apis/cert-manager.io/v1alpha3/clusterissuers/letsencrypt
  uid: ae21c4cb-ff1c-4fca-a180-2dae12097767
spec:
  acme:
    email: info@datawow.io
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
status:
  acme:
    lastRegisteredEmail: info@datawow.io
    uri: https://acme-v02.api.letsencrypt.org/acme/acct/86475970
  conditions:
  - lastTransitionTime: "2020-05-18T11:25:57Z"
    message: The ACME account was registered with the ACME server
    reason: ACMEAccountRegistered
    status: "True"
    type: Ready
